[project]
name = "database"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.14.1",
    "mlflow>=3.1",
    "numpy>=2.4.6",
    "openpyxl>=3.1.5",
    "optuna>=4.9.0",
    "pandas>=2.3.3",
    "scikit-learn>=1.9.0",
    "xgboost>=3.2.0",
    "torch",
    "loguru>=0.7.3",
    "lightgbm>=4.6.0",
    "catboost>=1.2.10",
    "pytorch-tabnet>=4.1.0",
]

[tool.uv.sources]
torch = [{ index = "pytorch-cpu" }]
torchvision = [{ index = "pytorch-cpu" }]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
